### PR TITLE
Feature / Implementation parity between WinBatch, DosBatch and ExecWith

### PR DESCRIPTION
**Pull request by sternenseemann**
## Motivation

The original motivation for this pull-request was to allow DosBatch-Sections to be executed with elevated privileges like WinBatch could be using `/RunElevated`. This change also has been [suggested in the OPSI forum](https://forum.opsi.org/viewtopic.php?f=5&t=8293&p=37679).

While implementing these changes it was apparent that the following desireable changes would also be easy to implement given the already necessary changes:

* `/Run*`-Parameters for `ExecWith`
* Output catching, `/showouput` and `getOutStreamFromSection` support for `WinBatch` ([these features have also - more or less - been asked for on the forum](https://forum.opsi.org/viewtopic.php?f=7&t=11500))

Having `/Run*` for `ExecWith` and `DosBatch` is great because it allows to use these more convenient sections in almost every case instead of `WinBatch` which is usually less convenient and harder to debug. I wished for this feature especially when working with PowerShell and Batch from OPSI.

The hard to debug problem also gets better with this pull request. Since `WinBatch` now supports catching its output, it is also logged and can be used for debugging.

## Implementation Approach

The basic idea for the implementation was to use `StartProcess` for all process execution, since it already implements executing processes with different levels of privilege, which seemed to be the most complicated task at hand. Since `StartProcess` lacked the feature to capture output, it was necessary to add that.

Then we could switch `ExecWith` and `DosBatch` to `StartProcess`, replacing `RunCommandAndCaptureOut`. Additionally it was possible to add output logging and display to `WinBatch`.

## Changes

* Fix build errors on Linux
* `osfunc` 
  * `StartProcess`
    * Generate a negative `Result` and a corresponding `Report` if an Exception occurs.
    * Accept a `TXStringList` as Parameter to which the output of the started process is written. Supported by `StartProcess_cp`, `StartProcess_cp_lu`, `StartProcess_cp_el` and `StartProcess_as`. Currently not supported by `StartProcess_se` (deprecated) and `StartProcess_se_as` (unused anyways).
    * Added a `showoutputflag` parameter which works like the `showouput` parameter of `RunCommandAndCaptureOut`, but also allows the calling function to handle creating and freeing the used `SystemInfo` (which is relevant for `WinBatch`). This is supported by all process starting types that also support output catching.
    * Allow inherting handles from the caller to the started process in `CreateProcess` for `StartProcess_cp_as`, `StartProcess_cp_el` and `StartProcess_cp_lu` (necessary for output capturing).
    * Allow output catching to be enabled and disabled with a `catchout` parameter.
  * `TShowOutputFlag`: new enum type used for `StartProcess`.
  * `SetFilePermissionForRunAs`: new function that adds an ACL entry to a given file to make it readable and executable for a given `TRunAs`-Level. It operates like this:
    * `traInvoker` (and RunElevated): no ACL entry required, ignore
    * `traLoggedOnUser`: use `usercontextSID` for ACL entry
    * `traAdmin` etc.: create temporary admin and then add ACL entry for `opsiSetupAdmin`
    * `traPcpatch`: fail with an error message, since it is not intended to be used with `traPcpatch`
* `osparser`
  * Reduce code duplication
    * move parsing of `/Run*`-Parameters to a central function, `RunAsForParameter`
    * move `parseAndCallWinBatch` to the top level and use it for parsing parameters of `processCall` as well
  * `DosBatch`
     * Use `StartProcess` exclusively instead of `RunCommandAndCaptureOut`
     * Log an error if an windows-only parameter has been used on macOS or Linux
     * Support all `/Run*`-Parameters that `WinBatch` has.
     * Call `SetFilePermissionForRunAs` after creating the temporary file to ensure the script can be executed, if the runas-level has less privileges than `SYSTEM` (e. g. `/RunAsLoggedOnAdmin` or `/RunAsLoggedOnUser`).
  * `WinBatch` / `processCall`
    * Return more a specific error message when an Windows-only parameter has been used on a non-Windows platform.
    * Log process output unless `/LetThemGo` was used.
    * Support displaying process output in `SystemInfo` window using `/showoutput`
  * `ExecWith`
    * Use `StartProcess` exclusively instead of `RunCommandAndCaptureOut`
    * Support all `/Run*`-Parameters that `WinBatch` has.
    * Call `SetFilePermissionForRunAs` after creating the temporary file to ensure the script can be executed
    * Add `/showoutput` parameter
    * Detect if an option is not supported on the current platform and log as an error, but continue executing.
  * `getOutStreamFromSection`: support `WinBatch` (note that the `StringList` will be empty if `/LetThemGo` was used)
  * `shellCall`: improve startup performance by only searching for `cmd64.exe.mui` in direct subdirs of  `C:\windows` instead of all of them recursively. This gets rid of some constant initial delay after calling `shellCall` and fixes a test (`processCall /WaitForWindowAppearing`) of `opsi-script-test` being marked as failed erroneously. 

For reviewing the code, I'd recommend go through the diffs commit by commit, I tried to group the changes into commits that make sense.

## Testing

I tested using custom opsi scripts for the specific new features and opsi-script-test in the following versions:

- [x] `opsi-script-test` from `stable` (4.12.1.5-1) on Windows
- [x] [fixed `opsi-script-test`](https://github.com/opsi-org/opsi-script-test/pull/1) from `experimental` (modified 4.12.3.9-2, fixed a bug in Winbatch tests) on Windows  
- [x] [fixed `opsi-script-test`](https://github.com/opsi-org/opsi-script-test/pull/2)  from `experimental` (modified 4.12.3.9-2, fixed a bug in `sleepSeconds` test) on Linux
- [x] [fixed `opsi-script-test` login script](https://github.com/opsi-org/opsi-script-test/pull/3) from `experimental` (modified 4.12.3.9-2, fixed a bug in `/RunAsLoggedOnUser` test) on Windows

## Open Questions

* Code Style / Implementation: I'm no regular Free Pascal Developer by any means, so I'd love to hear feedback on my code and areas to improve. Also I'm not sure if the code itself is self-explanatory and documented enough.
* Documentation: The changed usage should be documented in the opsi script manual. I'd propose I prepare a Pull Request for the documentation repository ~~in the next weeks~~.
* ~~More thorough testing: I tested mostly using simple OPSI scripts and different parameter combinations both on Linux and on running Windows OPSI Setups. Not sure if this could be improved.~~
* Performance: Checking every second, wether the process is still there, then reading a small amount of text and then waiting again could probably be improved for a smoother experience, especially when using `/showoutput`.
* I mostly use the `...A` version of WinApi functions. From my reckoning this should be no problem in all cases, but I'm not 100% sure, so I'd love feedback on that.

## Further Improvements

These are further improvements which came to mind while developing this. I might investigate them further in the future and submit additional pull requests. I'm not sure yet if they're worth implementing, so I'm looking for feedback on those, especially concerning `StartProcess_se` and logging.

* Add log level offset support for `StartProcess` and make log output more consistent with previous version overall for `DosBatch` and `ExecWith`. Log indentation is additionally kind of funky on GNU/Linux as well, although it was this way before.
* Switch `ExecPython` to `StartProcess`, add support for `/Run*` and `/showoutput` parameters. I haven't done this until now, because it requires adding section options to `ExecPython` by using a `winst` keyword or similar. This would also be possible for `powershellCall` and `shellCall`.
* Switch from `TProcess.CommandLine` which is deprecated to `TProcess.Executable` and `TProcess.Parameters`. This would probably require implementing something similar to `/EscapeStrings` for `WinBatch` and reworking the parameters of `StartProcess`.
* Implement Output Catching for `StartProcess_se` (and `StartProcess_se_as`). I didn't bother until now because the function is deprecated anyway.
* Add `processCall_list` variant of `processCall` which returns its output as `StringList`

## Conclusion

I'm looking forward to hearing from you on this pull request. I think it is a great change which would make packaging and debugging more convenient in many cases.

I'd also be happy to make adjustments to my code if you have any suggestions or feedback.

### CODE REVIEW

**Comment by JaWeRn** [comment]
Thank you for the request. Will be checked.

**Comment by sternenseemann** [comment]
Fixed accidental version number change on Linux via force push on my branch.

**Comment by sternenseemann** [comment]
I've started to work on updating the documentation to reflect my changes. You can view the diff [here](https://github.com/opsi-org/documentation/compare/stable...sternenseemann:feature/dosbatch-runelevated), but keep in mind it's not finished yet.

**Comment by JaWeRn** [comment]
Dear sternenseemann, 
we roughly checked your pull request. The main problem is that in the current state your code seems not to be combatible with older opsi-scripts which had to be given (e.g opsi-script-test failed). Furthermore your code manipulates file rights. This might be a security issue so we had to check it very carefully which is time expensive. Nevertheless you introduce some nice ideas and we will check if (adapted) parts of your code can be used in the future for opsi-script. (However note that unfortunatly this is currently not our main focus and thus it may take some time until you will find parts of your code included in opsi-script. I hope this is not to much disappointing to you)

Thank you very much for the pull requests and your huge effort!

Have a nice christmas and a happy new year!

Best wishes, 
your opsi-script development team

**Comment by sternenseemann** [comment]
Hi,

thank you for your reply! I actually hadn't noticed that `opsi-script-test` breaks, thanks for the heads up. My changes shouldn't change existing behaviour -- or at least should be possible to implement without breaking existing behaviour, so I will look into the breakages of `opsi-script-test` and work on fixing them.

The only behaviour I intentionally changed was undocumented (maybe even unintended) behaviour like how `ExecWith` ignores unsupported parameters, but `DosBatch` throws an `SyntaxError` when encountering one. If these kinds of changes also concern you, please send me a message, I can compile a list of those and we can discuss if some of those changes should be reverted which should be easily possible.

Regarding your security concerns: Please do check my implementation! I think design-wise it is fine, as only a specified normally-privileged user gets only gets read and execute access to the script file which is deleted after execution anyways. On thing on top of my head would be, if support for `traPcpatch` should be removed in `SetFilePermissionForRunAs`, since it is generally not used and opsi clients don't usally have that user (on the other hand there is no way as far as I can tell to make `winst32.exe` call `SetFilePermissionForRunAs` with `traPcPatch`, as it is never used really).

Also I'd be happy to answer to more specific questions or concerns of yours if that helps you. I'd also offer you to call me if that's more convenient for you.

Happy Holidays,

sternenseemann

**Comment by sternenseemann** [comment]
I've rebased my branch against the latest changes on `experimental` and noticed that currently the build of that branch fails on Windows and Linux. I've fixed those errors on a branch of mine and made a Pull Request out of it (see #6). Probably best to merge that one first, I'm still working on fixing `opsi-script-test` anyways.

**Comment by sternenseemann** [comment]
The last months I've been busy fixing bugs and inconsistencies brought to light by `opsi-script-test`. I made sure that my updated version of opsi-winst passes all tests of `opsi-script-test` (stable) 4.12.1.5-1 and `opsi-script-test` (experimental) 4.12.3.9-2. The first works flawlessly by now, the latter gave me a bit of trouble which I believe can easily be fixed:

First of all `opsi-script-test` experimental is currently broken on Linux due to an issue with the `sleepSeconds` test which also affects the latest normal experimental version of opsi-winst/script. It was however quite easy to fix and I've opened [a pull request resolving the issue](https://github.com/opsi-org/opsi-script-test/pull/2).

On windows `opsi-script-test` experimental kept failing for me in `Winbatch_testing msiexec` under strange circumstances: The error would only occur if `alltest` is turned `on`, but not if the affected test sub script (`winbatch.opsiscript`) was started individually. Turns out that `Winbatch_msi_standard` writes a log file inside of `$HomeTestFiles$` and fails if `$HomeTestFiles$` is not present (with exit code 1622 indicating an issue with writing the log file). This happens because the sub script before `winbatch.opsiscript` happens to delete the directory. I have also created [a pull request fixing this issue](https://github.com/opsi-org/opsi-script-test/pull/1) by ensuring that the directory is present.

The last issue does not affect current experimental opsi-winst, however, since `dummy.msi` behaves kind of strange if it can't write its log file:

* If it can't write to standard output, it just hangs up and never exits. This happens if called by normal experimental `Winbatch` or `processCall` since they don't provide the subprocess with a standard output. The test still succeeds because `/TimeoutSeconds 20` is used and the error will never be noticed.
* If it can write to standard output, it writes a single capital `F` and exits with 1622. This happens if it is started using `DosInAnIcon` for example (good for reproducing the issue in current opsi-winst) or in my fork of `opsi-winst` where `Winbatch` also captures the output. This leads to the test failing because it immediately fails with 1622 instead of hanging up completely and never exiting.

Since it is clearly not intentional that `dummy.msi` can't write to its log file in this case, I believe this is clearly an issue of `opsi-script-test` and [the pull request](https://github.com/opsi-org/opsi-script-test/pull/1) should be merged.

This also means that (naturally) behavior of `Winbatch` changes between `experimental` and my version for some processes that are started. I believe though that this does not really matter since a) these cases are pretty rare and b) the behavior changes generally for the better: It is a more normal environment for a process to have a standard output and standard error than not. If the change is still of concern, output capturing for WinBatch could be turned off using a parameter or maybe even turned off by default. Just let me know what you think on this issue.

Below is a list of the most notable fixes I added. Additionally I have updated the list of changes in the [first comment](https://github.com/opsi-org/lazarus/pull/5#issue-350800319).

* Fixed a bug where StartProcess would hang completely and become unresponsive if `/LetThemGo` and `/WaitForWindowAppearing` were used.
* Fixed various issues with `ExecWith` parameter parsing. It behaves now like on the main branch again.
* Improve startup performance of `shellCall`. Previously searching for `cmd64.exe.mui` took so long that a timing-related test of `opsi-script-test` failed.
* Fixed issue with processes freezing or behaving differently when started using `/LetThemGo`

I'd be great if you could test my pull request again and confirm that my fixes work and to hear some feedback on this. I'd recommend to use [my `opsi-script-test` branch](https://github.com/sternenseemann/opsi-script-test/tree/experimental) which contains both mentioned fixes already.

Additionally, I'd love hearing if and how this PR could be merged. We'd be willing to invest some of our support hours for you to look into it, especially the security-related code. Also I'd be happy to fix any issues that comes up or change anything that prevents this PR from becoming part of opsi-script.

I understand you are busy generally, but hearing on this in the near future would be wonderful, since keeping this pull request free of merge conflict means that I spend quite a bit of time rebasing against your `experimental` branch every time something changes in `osparser.pas` or `osfunc.pas`.

Kind regards,

sternenseemann

PS: Also if some tests fail, a log and the affected tests would be great. I know that the `getHWBiosInfoMap` test fails on Linux sometimes (fail is not reproducable I don't really know what triggers it), but I have confirmed that it is unrelated to my changes, since it also happens with normal `opsi-script`.

**Comment by JaWeRn** [comment]
Dear Sternenseemann,
Thank you again for your effort to improve opsi-script! We will discuss your suggestions in the near future and get back to you. At the moment we are all busy in preparing the opsiconf next week in Mainz (02. - 03.04.2020; www.opsiconf.org) Maybe you are there? I think we can give you a more detailed response earliest the week after.

Best wishes,
Your opsi development team

**Comment by sternenseemann** [comment]
Sadly I can't make it, but I hope it'll be fun and insightful. I'm looking forward to your feedback!

In the meantime I've had a look at the `login.opsiscript` of `opsi-script-test` which was also failing with the latest `experimental` `opsi-script`. I have been able to resolve the issue and opened a [pull request for it](https://github.com/opsi-org/opsi-script-test/pull/3). The fixed tests succeed for both the latest `experimental` `opsi-script` as well as my version. Additionally, I have updated [my `experimental` branch](https://github.com/sternenseemann/opsi-script-test/tree/experimental) to include this `opsi-script-test` fix as well.

**Comment by JaWeRn** [comment]
Dear sternenseemann,
please contact us directly (j.werner@uib.de) with real name then we will get back to you to discuss your merge request in more detail.

Best wishes,
Your opsi development team

**Comment by sternenseemann** [comment]
I've fixed the `OemToAnsi` issue that was pointed out.

There are currently a few merge conflicts in `osparser.pas`. I've chosen not to fix them for now, since rebasing almost 40 commits against `experimental` is always a lot of work and merging the changes into my feature branch doesn't make a lot of sense. It's probably easiest if you guys just manually merge this PR and solve the conflicts then.

**Comment by sternenseemann** [comment]
This can be closed now, right?

**Comment by JaWeRn** [comment]
Yes, in our opinion this can be closed.

Am 16.12.2020 um 19:58 schrieb sternenseemann:

**Comment by sternenseemann** [comment]
Alright :) Almost missed the merge, really happy!!

**Pull request closed without merging**
